#!/bin/bash

# check if workbench folder exists, create if it doesn't
if [ ! -d "$HOME/.workbench" ]; then
  mkdir "$HOME/.workbench"
fi

# Check if the required programs are installed
if ! command -v yt-dlp &> /dev/null
then
    echo "yt-dlp could not be found. Please install it."
    exit
fi

if ! command -v ffmpeg &> /dev/null
then
    echo "ffmpeg could not be found. Please install it."
    exit
fi

# Get the arguments
link="$1"
start="$2"
end="$3"
result_file_path="$4"

# download video to workbench folder
cd "$HOME/.workbench"

yt-dlp -f 'bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[height<=720][ext=mp4]/best[height<=480]/best' \
    --downloader ffmpeg --downloader-args "ffmpeg_i:-ss ${start} -to ${end} " \
    --merge-output-format mp4 -o "source_${result_file_path}" "$link"

# Compress the video with ffmpeg
ffmpeg -i "source_${result_file_path}" -vcodec h264 -s hd720 -crf 28 -acodec aac "${result_file_path}"

# Remove the downloaded video file
# rm video.*

