telegram:
  name: ${STUDY_BOT_NAME}
  token: ${STUDY_BOT_TOKEN}
  useWebhook: false
  webhookUrl: https://studycloud.live:443
  webhookPath: /naevis

  command:
    start: Начало работы с ботом
    clip: "Вырезать клип из ютуб видео (использование: /help clip)"
    clip_gif: "Вырезать гифку из ютуб видео (использование: /help clip_gif)"
    clip_subs: "Вырезать клип из ютуб видео с субтитрами (использование: /help clip_subs)"
    create_room: Создать комнату для совместной учебы
    join_room: Присоединиться к комнате для совместной учебы
    study: Начать учебную сессию

  message:
    error: Произошла ошибка при исполнении команды
    help: |-
      Вы используете бота, который умеет вырезать клипы из ютуб видео.
      
      Команда "help" выводит информацию об использовании других команд. Например, для получения помощи по команде "clip" введите "/help clip".
